### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by killerraj369** [killerraj369/Resume-Maker#1]

**Comment by pranavsuriya-sr** [comment]
I would like to work on this issue....Please assign this to me.

**Comment by YashGadia** [comment]
@killerraj369 Could you assign this to me? Also please specify what changes are to be done in Readme.md file.

**Comment by YashGadia** [comment]
@killerraj369 I've updated the Readme.md file. Can you please check and review it? I am attaching the screenshots for all the changes that I've made.
![R1](https://user-images.githubusercontent.com/101691073/195396376-7571835f-7861-46ba-9eac-9b3f3bf972c3.JPG)
![R2](https://user-images.githubusercontent.com/101691073/195396401-224e222b-29af-4af2-8b1b-70accefd43f3.JPG)
![R3](https://user-images.githubusercontent.com/101691073/195396417-fdbd8735-9e0f-4bce-a47f-e0eaee522ac2.JPG)
![R4](https://user-images.githubusercontent.com/101691073/195396430-3065d027-dc9d-450a-8440-5bdcc7e50415.JPG)

**Comment by killerraj369** [comment]
Yes make a PR
