### ISSUE TITLE
Enhance Form HTML

### ISSUE THREAD

**Issue by killerraj369** [killerraj369/Resume-Maker#2]

**Comment by YashGadia** [comment]
@killerraj369 Could you assign this to me?

**Comment by killerraj369** [comment]
@YashGadia Sure Work upon it !

**Comment by YashGadia** [comment]
@killerraj369 I have solved the issue. Can you please check and review my work? I am attaching the screen recording for all the changes that I've made. 

https://user-images.githubusercontent.com/101691073/195328158-a9a2c2bf-f364-4045-99eb-9364a2a74e2c.mp4

**Comment by killerraj369** [comment]
Good ! Make a PR for your changes
