### ISSUE TITLE
Logo design 

### ISSUE THREAD

**Issue by Matthieu-ui** [killerraj369/Resume-Maker#27]
Current page logo could use some rework. I can make svg, take out the background and adjust colors. 
or new design? 
Let me know if this is something I can do to help! #hacktoberfest!!
![images](https://user-images.githubusercontent.com/77665167/195728536-48147a7c-af3b-4808-90f5-8d94abb16d0a.png)

**Comment by killerraj369** [comment]
Yes, you can make a Good logo and then raise a PR
