### ISSUE TITLE
Image is not opening

### ISSUE THREAD

**Issue by Kritika30032002** [killerraj369/Resume-Maker#36]
![Screenshot (19450)](https://user-images.githubusercontent.com/83400697/195842206-ef993f22-141d-488b-b5b9-150ac617acb8.png)

**Comment by killerraj369** [comment]
Do you wish to work on this issue ?

**Comment by anupandey1** [comment]
hii @killerraj369 @Kritika30032002 
I want to work on this
please assign a hackoctober tag to it

**Comment by Kritika30032002** [comment]
> Do you wish to work on this issue ?

yes

**Comment by killerraj369** [comment]
Issue has  been resolved
