### ISSUE TITLE
I want to add scroll to top button .

### ISSUE THREAD

**Issue by AshishSharma1203** [killerraj369/Resume-Maker#40]
I want to add a scroll to the top button which directly jumps to the top of the website.

**Comment by AshishSharma1203** [comment]
Please assign me this issue  @killerraj369 .

**Comment by AshishSharma1203** [comment]
Are you going to work yourself on this ???

**Comment by killerraj369** [comment]
@AshishSharma1203 Go on Project is yours,
Add a good scroll up button  !

**Comment by AshishSharma1203** [comment]
> @AshishSharma1203 Go on Project is yours, Add a good scroll up button !

I have made the required changes in the code to implement the feature , please verify this and merge it .

**Comment by killerraj369** [comment]
Thanks @AshishSharma1203 . I am closing the issue now
