### ISSUE TITLE
Improve logo

### ISSUE THREAD

**Issue by CoderAayush2104** [killerraj369/Resume-Maker#43]
![logo](https://user-images.githubusercontent.com/95217441/195971708-31575d16-e2ea-4338-be9f-79aa6fef28c8.jpg)
The logo seems very bad. I can improve the logo for you.

**Comment by aakash1233333** [comment]
please assigned it to me

**Comment by aakash1233333** [comment]
Thanks doing this

**Comment by aakash1233333** [comment]
i have done but unable to contribute it because my first pull request is pending.

**Comment by aakash1233333** [comment]
done

**Comment by aakash1233333** [comment]
please see my logo
