### ISSUE TITLE
Light/Dark Mode Toggle Button

### ISSUE THREAD

**Issue by theravi04** [killerraj369/Resume-Maker#44]
Adding a toggle button to switch from light to dark mode.
@killerraj369 kindly assign me this under HacktoberFest 2022.

**Comment by ghost** [comment]
Hi @killerraj369 can I be assigned this issue under HacktoberFest 2022

**Comment by ghost** [comment]
Hi @killerraj369 may you please accept my pull PR #57. 
I have added a toggle button that allows you to switch between dark/light mode.
