### ISSUE TITLE
Improving layout of Why Build resume page.

### ISSUE THREAD

**Issue by Kritika30032002** [killerraj369/Resume-Maker#45]
Want to improve layout of "Why Build my resume with our Website?"  using CSS flexbox.

Demo what I want to do is attached .Also more effects will be added.

Assign this to me!!

![Screenshot (19459)](https://user-images.githubusercontent.com/83400697/196021113-ad108270-bfe3-492f-9723-75e09737eaee.png)

**Comment by killerraj369** [comment]
Ok, Will Review.
