### ISSUE TITLE
Remove Login Sign Up buttons instead add Dark Mode/Light Mode and Github Repo Link ( Top Right ) 

### ISSUE THREAD

**Issue by killerraj369** [killerraj369/Resume-Maker#46]
Hey Contributors,
This is an easy task. You can easily solve this issue

**Comment by aakash1233333** [comment]
assign it to me

**Comment by killerraj369** [comment]
don't forget to mention issue number in PR

**Comment by aakash1233333** [comment]
Please see my logo one and merge it thanks

**Comment by aakash1233333** [comment]
Issue #43 which was assigned to me I have done

**Comment by aakash1233333** [comment]
please merge it i have done 2-3 times.thanks
added logo also

**Comment by aakash1233333** [comment]
Please merge it please

**Comment by killerraj369** [comment]
Make PR

**Comment by aakash1233333** [comment]
Already done it
LOGO ADDED name

**Comment by aakash1233333** [comment]
Please see to it

**Comment by aakash1233333** [comment]
Please see to it you assigned me #43 logo enhancement and i have done first
you say to change it then I changed it and now please check towards it .It
is my 4th PR towards your project.
Thanks

**Comment by killerraj369** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/87773889/196044159-56d7b755-c45a-4c7b-99f1-07cb2e4abcb6.png)

**Comment by killerraj369** [comment]
https://www.linkedin.com/in/vaibhav-raj-229967218/ connect me on linkedin
