### ISSUE TITLE
[Feature]: Adding Social Icons to the footer with Hover effects

### ISSUE THREAD

**Issue by Kritika30032002** [killerraj369/Resume-Maker#53]
Adding Social Icons to the footer with Hover effects

Assign this issue to me!!

**Comment by Kritika30032002** [comment]
@killerraj369

**Comment by MartinMaphutseng** [comment]
@MartinMaphutseng 
May I please be assigned this issue.

**Comment by killerraj369** [comment]
This task has been completed
