### ISSUE TITLE
enhanching people about video resume demo

### ISSUE THREAD

**Issue by Swastik200** [killerraj369/Resume-Maker#6]
its going to be modern era with acceptance of video resume

**Comment by killerraj369** [comment]
Hey swastik,
Can you please elaborate what you are gonna do .

**Comment by Swastik200** [comment]
Video resume is a great idea ahead  ...so telling people about its effect

**Comment by Swastik200** [comment]
Sir adding some points on video resuming giving its referring video.
...some points
